### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by guer0125** [guer0125/registration-form#1]
Hi, I cant seem to get passed this point.
im kinda stuck. could you please help me lol
@muxlowc

**Comment by muxlowc** [comment]
@guer0125 

1) You're missing your "unit" classes - you need to have "unit" and then any unit sizes - right now your units don't know theyre units, which is why theyre getting squished

2) remove your "grid" tag where your Mission Statement is - you don't need it here
3) in your CSS add your grey background on your html, and white background on your form

4) In order to get space between your two inputs, put this into your css:

@media only screen and (min-width: 60em) {

  .space-right {
    padding-right: .5rem;
  }

  .space-left {
    padding-left: .5rem;
  }

}

And remember to name your tags in html accordingly!

Hope this helps you move along :)

**Comment by guer0125** [comment]
Hi, it helped a lot

I'm not sure why my white is in the right place but my text is not. 

also I couldn't find how to do the `Request to join the mission` for the email subject

I did all the input[id][name], select[id][name], textarea[id][name] but **markbot is saying that is still expecting them.**

and lastly, it's expecting input[type="hidden"] not sure where is goes.

thank you for all your help

**Comment by muxlowc** [comment]
@guer0125 

1) for the type=hidden, add this code down after your button, but before you close your form:
    `<input type="hidden" name="_subject" value="Request to join the mission">`
(it's kind of a left over from something Thomas used to teach)

2) So it looks like you're missing your "name="" " tags - They should look something like this:
```
<label for="name">Name</label>
          <input id="name" name="name" required>
```
You'll need them pretty much everywhere you have an ID 

3) you can remove your section & Div that you have around your form for this assignment, and add these classes to your form: "gutter pad-t-2 pad-b-2 max-length"
